<a href="https://colab.research.google.com/github/yashverma165/Meachine_learning/blob/main/logistic_implementaion_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## LOGESTIC Regression Implementation

In [ ]:
from sklearn.datasets import load_iris

In [ ]:
dataset=load_iris()

In [ ]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
dataset['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [ ]:
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)

In [ ]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [ ]:
df['target']=dataset.target

In [ ]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [ ]:
df_copy=df[df['target']!=2]

In [ ]:
df_copy.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

### Independent and dependent features

In [ ]:
X=df_copy.iloc[:,:-1]
Y=df_copy.iloc[:,-1]


In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
# Train test Split
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.20,random_state=44 )

In [ ]:
classifier=LogisticRegression()
classifier.fit(X_train,y_train)

LogisticRegression()

In [ ]:
# prediction
y_pred=classifier.predict(X_test)
y_pred

array([0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1])

In [ ]:
y_test

42    0
54    1
27    0
93    1
39    0
65    1
7     0
26    0
24    0
60    1
86    1
30    0
37    0
70    1
19    0
99    1
96    1
33    0
66    1
68    1
Name: target, dtype: int64

### Cunfusion matrix , Accuracy score, Classification Report

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [ ]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[10  0]
 [ 0 10]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



## Hyperparameter Tuning

### GridSearchCV


In [ ]:
import warnings
from sklearn.model_selection import GridSearchCV
warnings.filterwarnings('ignore')

In [ ]:
parameters={'penalty':('l1','l2','elasticnet',None),'C':[1,5,10,20,35]}

In [ ]:
clt=GridSearchCV(classifier,param_grid=parameters,cv=5)

In [ ]:
# Spliting of train data to validation data
clt.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 5, 10, 20, 35],
                         'penalty': ('l1', 'l2', 'elasticnet', None)})

In [ ]:
clt.best_params_

{'C': 1, 'penalty': 'l2'}

In [ ]:
classifier=LogisticRegression(C=1,penalty='l2')

In [ ]:
classifier.fit(X_train,y_train)

LogisticRegression(C=1)

In [ ]:
y_pred=classifier.predict(X_test)
y_pred

array([0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1])

In [ ]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[10  0]
 [ 0 10]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



#3. Randomized SearchCV

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
random_clt=RandomizedSearchCV(LogisticRegression(),param_distributions=parameters,cv=5)

In [ ]:
random_clt.fit(X_train,y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [1, 5, 10, 20, 35],
                                        'penalty': ('l1', 'l2', 'elasticnet',
                                                    None)})

In [ ]:
random_clt.best_params_

{'penalty': 'l2', 'C': 20}

In [ ]:
LogisticRegression(C=20,penalty='l2')

LogisticRegression(C=20)